version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  labels:
  - kind/dependency
  - do-not-merge/work-in-progress
  ignore:
  - dependency-name: Microsoft.Toolkit.Mvvm
    versions:
    - 7.0.0
    - 7.0.0-preview4
    - 7.0.0-preview5
  - dependency-name: Xamarin.AndroidX.Lifecycle.LiveData
    versions:
    - 2.2.0.4
    - 2.3.0
    - 2.3.0.1
  - dependency-name: Xamarin.AndroidX.RecyclerView
    versions:
    - 1.1.0.6
    - 1.1.0.7
    - 1.1.0.8
  - dependency-name: Uno.UI
    versions:
    - 3.1.12
    - 3.1.14
    - 3.5.1
  - dependency-name: Microsoft.AppCenter.Crashes
    versions:
    - 4.1.0
  - dependency-name: Microsoft.AppCenter.Analytics
    versions:
    - 4.1.0
  - dependency-name: Xamarin.AndroidX.Browser
    versions:
    - 1.3.0.4
  - dependency-name: Com.Airbnb.Android.Lottie
    versions:
    - 3.5.0
